/* Bussiness Related Queries. */

select * from customer limit 20;

--1. What is the total revenue generated by Male VS Female Customers ?

Select Gender, Sum(purchase_amount) as Total_Revenue From customer 
Group By Gender
Order By Total_Revenue desc;

-- 2. Which customer used a discount but still spent more then the average purchase amount ?

Select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount>=(Select avg(purchase_amount) from customer);
    
-- 3. Which are top 5 products with the highest average review rating ?

Select item_purchased, Round(avg(review_rating::numeric),2) as "Average Product Rating" from customer
group by  item_purchased
order by avg(review_rating)
limit 5;   

--4. Compare the average purchase amount between standard and express shipping ?

Select shipping_type, Round(avg(purchase_amount),2) as "Average Purchase Amount" From customer 
where shipping_type in ('Standard','Express')
group by shipping_type
order by "Average Purchase Amount" desc;

-- 5.Do subcribes customer spent more ? Compare average spend and total revenue between subscribers & non subcribers ?

Select subscription_status,count(customer_id) as "Total Customer",
Round(avg(purchase_amount),2) as "Average Spend",
Round(Sum(purchase_amount),2) as "Total Revenue"
from Customer
group by subscription_status;

-- 6. Which 5 Products have the highest percentage of purchases with discount applied ?

Select item_purchased , Round(100*Sum(Case when discount_applied='Yes' Then 1 Else 0 End)/count(*),2) as discount_rate 
from Customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7. Segment Customer into New, Returning, and loyal based on their total number of previous purchases
--, and show the count of each segment?
Select * from customer

With customer_type as (
Select customer_id,previous_purchases,
Case 
	When previous_purchases=1 Then 'New'
	When previous_purchases between 2 and 10 then 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer	
	)
Select customer_segment ,count(*) as "Number of Customers"
from customer_type
group by customer_segment
order by "Number of Customers" desc

-- 8 What are the top 3 most purchased products within each category ?

with item_counts as (
Select category, item_purchased, count(customer_id) as total_orders,
Row_Number() OVER (partition by category order by count(customer_id) desc) as item_mark from customer
group by category, item_purchased
)

Select item_mark ,category , item_purchased,total_orders
from item_counts 
where item_mark<=3;

--9 Are customers who are repeat buyers means (more then 5 previous purchases) also likely to subscriptions ?

Select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases>5
group by subscription_status;

--10 What is the revenue contribution of each age-group

Select age_group, sum(purchase_amount) as table_revenue
from customer
group by age_group
order by table_revenue desc 




